apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kondense
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]